// <auto-generated />
using System;
using Koncierge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Koncierge.Data.Migrations
{
    [DbContext(typeof(KonciergeDbContext))]
    [Migration("20250628131823_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KonciergeForwardNamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KonciergeForwardNamespaceId");

                    b.ToTable("Forwards");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForwardAdditionalConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KonciergeForwardId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KonciergeForwardId");

                    b.ToTable("ForwardLinkedConfigs");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForwardContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KonciergeKubeConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KonciergeKubeConfigId");

                    b.ToTable("ForwardContexts");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForwardNamespace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KonciergeForwardContextId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KonciergeForwardContextId");

                    b.ToTable("ForwardNameSpaces");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeKubeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KubeConfigs");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForward", b =>
                {
                    b.HasOne("Koncierge.Domain.Entities.KonciergeForwardNamespace", null)
                        .WithMany("Forwards")
                        .HasForeignKey("KonciergeForwardNamespaceId");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForwardAdditionalConfig", b =>
                {
                    b.HasOne("Koncierge.Domain.Entities.KonciergeForward", null)
                        .WithMany("AdditionalConfigs")
                        .HasForeignKey("KonciergeForwardId");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForwardContext", b =>
                {
                    b.HasOne("Koncierge.Domain.Entities.KonciergeKubeConfig", null)
                        .WithMany("Contexts")
                        .HasForeignKey("KonciergeKubeConfigId");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForwardNamespace", b =>
                {
                    b.HasOne("Koncierge.Domain.Entities.KonciergeForwardContext", null)
                        .WithMany("Namespaces")
                        .HasForeignKey("KonciergeForwardContextId");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForward", b =>
                {
                    b.Navigation("AdditionalConfigs");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForwardContext", b =>
                {
                    b.Navigation("Namespaces");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeForwardNamespace", b =>
                {
                    b.Navigation("Forwards");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KonciergeKubeConfig", b =>
                {
                    b.Navigation("Contexts");
                });
#pragma warning restore 612, 618
        }
    }
}
