//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonciergeUI.Translations.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enumerations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enumerations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KonciergeUI.Translations.Resources.Enumerations", typeof(Enumerations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string forward_status_running {
            get {
                return ResourceManager.GetString("forward_status.running", resourceCulture);
            }
        }
        
        public static string forward_status_stopped {
            get {
                return ResourceManager.GetString("forward_status.stopped", resourceCulture);
            }
        }
        
        public static string forward_status_starting {
            get {
                return ResourceManager.GetString("forward_status.starting", resourceCulture);
            }
        }
        
        public static string forward_status_reconnecting {
            get {
                return ResourceManager.GetString("forward_status.reconnecting", resourceCulture);
            }
        }
        
        public static string forward_status_stopping {
            get {
                return ResourceManager.GetString("forward_status.stopping", resourceCulture);
            }
        }
        
        public static string forward_status_failed {
            get {
                return ResourceManager.GetString("forward_status.failed", resourceCulture);
            }
        }
    }
}
