//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonciergeUI.Translations.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forwards {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forwards() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KonciergeUI.Translations.Resources.Forwards", typeof(Forwards).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string create_forward_title {
            get {
                return ResourceManager.GetString("create_forward_title", resourceCulture);
            }
        }
        
        public static string local_port {
            get {
                return ResourceManager.GetString("local_port", resourceCulture);
            }
        }
        
        public static string remote_port {
            get {
                return ResourceManager.GetString("remote_port", resourceCulture);
            }
        }
        
        public static string protocol {
            get {
                return ResourceManager.GetString("protocol", resourceCulture);
            }
        }
        
        public static string linked_secrets {
            get {
                return ResourceManager.GetString("linked_secrets", resourceCulture);
            }
        }
        
        public static string link_a_secret {
            get {
                return ResourceManager.GetString("link_a_secret", resourceCulture);
            }
        }
        
        public static string select_item_link {
            get {
                return ResourceManager.GetString("select_item_link", resourceCulture);
            }
        }
        
        public static string start_forward_title {
            get {
                return ResourceManager.GetString("start_forward_title", resourceCulture);
            }
        }
        
        public static string start_forward {
            get {
                return ResourceManager.GetString("start_forward", resourceCulture);
            }
        }
        
        public static string message_failed_start {
            get {
                return ResourceManager.GetString("message_failed_start", resourceCulture);
            }
        }
        
        public static string edit_forward_title {
            get {
                return ResourceManager.GetString("edit_forward_title", resourceCulture);
            }
        }
        
        public static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        public static string cmd_start {
            get {
                return ResourceManager.GetString("cmd_start", resourceCulture);
            }
        }
        
        public static string cmd_stop {
            get {
                return ResourceManager.GetString("cmd_stop", resourceCulture);
            }
        }
        
        public static string message_added_clipboard {
            get {
                return ResourceManager.GetString("message_added_clipboard", resourceCulture);
            }
        }
        
        public static string message_fail_clipboard {
            get {
                return ResourceManager.GetString("message_fail_clipboard", resourceCulture);
            }
        }
        
        public static string service_type {
            get {
                return ResourceManager.GetString("service_type", resourceCulture);
            }
        }
        
        public static string service_name {
            get {
                return ResourceManager.GetString("service_name", resourceCulture);
            }
        }
        
        public static string service_namespace {
            get {
                return ResourceManager.GetString("service_namespace", resourceCulture);
            }
        }
    }
}
