//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonciergeUI.Translations.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KonciergeUI.Translations.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string confirm_dialog_title {
            get {
                return ResourceManager.GetString("confirm_dialog_title", resourceCulture);
            }
        }
        
        public static string confirm_dialog_message {
            get {
                return ResourceManager.GetString("confirm_dialog_message", resourceCulture);
            }
        }
        
        public static string confirm_dialog_ok_label {
            get {
                return ResourceManager.GetString("confirm_dialog_ok_label", resourceCulture);
            }
        }
        
        public static string confirm_dialog_cancel_label {
            get {
                return ResourceManager.GetString("confirm_dialog_cancel_label", resourceCulture);
            }
        }
        
        public static string k8s_configmaps {
            get {
                return ResourceManager.GetString("k8s_configmaps", resourceCulture);
            }
        }
        
        public static string k8s_secrets {
            get {
                return ResourceManager.GetString("k8s_secrets", resourceCulture);
            }
        }
        
        public static string crud_cancel {
            get {
                return ResourceManager.GetString("crud_cancel", resourceCulture);
            }
        }
        
        public static string crud_create {
            get {
                return ResourceManager.GetString("crud_create", resourceCulture);
            }
        }
        
        public static string info_descrioption {
            get {
                return ResourceManager.GetString("info_descrioption", resourceCulture);
            }
        }
        
        public static string info_version {
            get {
                return ResourceManager.GetString("info_version", resourceCulture);
            }
        }
        
        public static string info_build {
            get {
                return ResourceManager.GetString("info_build", resourceCulture);
            }
        }
        
        public static string info_channel {
            get {
                return ResourceManager.GetString("info_channel", resourceCulture);
            }
        }
        
        public static string crud_save {
            get {
                return ResourceManager.GetString("crud_save", resourceCulture);
            }
        }
        
        public static string crud_edit {
            get {
                return ResourceManager.GetString("crud_edit", resourceCulture);
            }
        }
        
        public static string crud_remove {
            get {
                return ResourceManager.GetString("crud_remove", resourceCulture);
            }
        }
        
        public static string random {
            get {
                return ResourceManager.GetString("random", resourceCulture);
            }
        }
        
        public static string k8s_context {
            get {
                return ResourceManager.GetString("k8s_context", resourceCulture);
            }
        }
        
        public static string modified {
            get {
                return ResourceManager.GetString("modified", resourceCulture);
            }
        }
    }
}
