//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonciergeUI.Translations.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KonciergeUI.Translations.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string add_kubeconfig {
            get {
                return ResourceManager.GetString("add_kubeconfig", resourceCulture);
            }
        }
        
        public static string start_forward {
            get {
                return ResourceManager.GetString("start_forward", resourceCulture);
            }
        }
        
        public static string create_template {
            get {
                return ResourceManager.GetString("create_template", resourceCulture);
            }
        }
        
        public static string tab_pods {
            get {
                return ResourceManager.GetString("tab_pods", resourceCulture);
            }
        }
        
        public static string tab_services {
            get {
                return ResourceManager.GetString("tab_services", resourceCulture);
            }
        }
        
        public static string empty_title {
            get {
                return ResourceManager.GetString("empty_title", resourceCulture);
            }
        }
        
        public static string empty_subtitle {
            get {
                return ResourceManager.GetString("empty_subtitle", resourceCulture);
            }
        }
        
        public static string loading_cluster {
            get {
                return ResourceManager.GetString("loading_cluster", resourceCulture);
            }
        }
        
        public static string no_clusters_found {
            get {
                return ResourceManager.GetString("no_clusters_found", resourceCulture);
            }
        }
        
        public static string select_cluster {
            get {
                return ResourceManager.GetString("select_cluster", resourceCulture);
            }
        }
        
        public static string default_namespace {
            get {
                return ResourceManager.GetString("default_namespace", resourceCulture);
            }
        }
        
        public static string pod_search {
            get {
                return ResourceManager.GetString("pod_search", resourceCulture);
            }
        }
        
        public static string service_search {
            get {
                return ResourceManager.GetString("service_search", resourceCulture);
            }
        }
        
        public static string pod_namespace {
            get {
                return ResourceManager.GetString("pod_namespace", resourceCulture);
            }
        }
        
        public static string pod_status {
            get {
                return ResourceManager.GetString("pod_status", resourceCulture);
            }
        }
        
        public static string pod_name {
            get {
                return ResourceManager.GetString("pod_name", resourceCulture);
            }
        }
        
        public static string pod_ports {
            get {
                return ResourceManager.GetString("pod_ports", resourceCulture);
            }
        }
        
        public static string pod_actions {
            get {
                return ResourceManager.GetString("pod_actions", resourceCulture);
            }
        }
        
        public static string pod_loading {
            get {
                return ResourceManager.GetString("pod_loading", resourceCulture);
            }
        }
        
        public static string pod_notfound_search {
            get {
                return ResourceManager.GetString("pod_notfound_search", resourceCulture);
            }
        }
        
        public static string pod_notfound {
            get {
                return ResourceManager.GetString("pod_notfound", resourceCulture);
            }
        }
        
        public static string service_actions {
            get {
                return ResourceManager.GetString("service_actions", resourceCulture);
            }
        }
        
        public static string service_namespace {
            get {
                return ResourceManager.GetString("service_namespace", resourceCulture);
            }
        }
        
        public static string service_name {
            get {
                return ResourceManager.GetString("service_name", resourceCulture);
            }
        }
        
        public static string service_type {
            get {
                return ResourceManager.GetString("service_type", resourceCulture);
            }
        }
        
        public static string pod_refresh {
            get {
                return ResourceManager.GetString("pod_refresh", resourceCulture);
            }
        }
        
        public static string service_refresh {
            get {
                return ResourceManager.GetString("service_refresh", resourceCulture);
            }
        }
        
        public static string service_loading {
            get {
                return ResourceManager.GetString("service_loading", resourceCulture);
            }
        }
        
        public static string service_notfound_search {
            get {
                return ResourceManager.GetString("service_notfound_search", resourceCulture);
            }
        }
        
        public static string service_notfound {
            get {
                return ResourceManager.GetString("service_notfound", resourceCulture);
            }
        }
        
        public static string pod_all_namespaces {
            get {
                return ResourceManager.GetString("pod_all_namespaces", resourceCulture);
            }
        }
        
        public static string service_all_namespaces {
            get {
                return ResourceManager.GetString("service_all_namespaces", resourceCulture);
            }
        }
        
        public static string service_all_types {
            get {
                return ResourceManager.GetString("service_all_types", resourceCulture);
            }
        }
        
        public static string pod_all_statuses {
            get {
                return ResourceManager.GetString("pod_all_statuses", resourceCulture);
            }
        }
        
        public static string pod_namespaces {
            get {
                return ResourceManager.GetString("pod_namespaces", resourceCulture);
            }
        }
        
        public static string service_namespaces {
            get {
                return ResourceManager.GetString("service_namespaces", resourceCulture);
            }
        }
        
        public static string pod_statuses {
            get {
                return ResourceManager.GetString("pod_statuses", resourceCulture);
            }
        }
        
        public static string service_types {
            get {
                return ResourceManager.GetString("service_types", resourceCulture);
            }
        }
        
        public static string page_all {
            get {
                return ResourceManager.GetString("page_all", resourceCulture);
            }
        }
        
        public static string page_pod_per {
            get {
                return ResourceManager.GetString("page_pod_per", resourceCulture);
            }
        }
        
        public static string page_service_per {
            get {
                return ResourceManager.GetString("page_service_per", resourceCulture);
            }
        }
        
        public static string resource {
            get {
                return ResourceManager.GetString("resource", resourceCulture);
            }
        }
    }
}
