//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonciergeUI.Translations.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KonciergeUI.Translations.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string add_kubeconfig {
            get {
                return ResourceManager.GetString("add_kubeconfig", resourceCulture);
            }
        }
        
        public static string start_forward {
            get {
                return ResourceManager.GetString("start_forward", resourceCulture);
            }
        }
        
        public static string create_template {
            get {
                return ResourceManager.GetString("create_template", resourceCulture);
            }
        }
        
        public static string tab_pods {
            get {
                return ResourceManager.GetString("tab_pods", resourceCulture);
            }
        }
        
        public static string tab_services {
            get {
                return ResourceManager.GetString("tab_services", resourceCulture);
            }
        }
        
        public static string empty_title {
            get {
                return ResourceManager.GetString("empty_title", resourceCulture);
            }
        }
        
        public static string empty_subtitle {
            get {
                return ResourceManager.GetString("empty_subtitle", resourceCulture);
            }
        }
    }
}
