//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonciergeUI.Translations.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KonciergeUI.Translations.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string save_template {
            get {
                return ResourceManager.GetString("save_template", resourceCulture);
            }
        }
        
        public static string template_name {
            get {
                return ResourceManager.GetString("template_name", resourceCulture);
            }
        }
        
        public static string template_description {
            get {
                return ResourceManager.GetString("template_description", resourceCulture);
            }
        }
        
        public static string cmd_start {
            get {
                return ResourceManager.GetString("cmd_start", resourceCulture);
            }
        }
        
        public static string cmd_stop {
            get {
                return ResourceManager.GetString("cmd_stop", resourceCulture);
            }
        }
        
        public static string port_already_used {
            get {
                return ResourceManager.GetString("port_already_used", resourceCulture);
            }
        }
        
        public static string start_template_title {
            get {
                return ResourceManager.GetString("start_template_title", resourceCulture);
            }
        }
    }
}
